### ISSUE TITLE
crash report. 

### ISSUE THREAD

**Issue by microgomi** [BranchMetrics/Branch-iOS-SDK#90] opened 2015-04-29 05:35 UTC
Hi branch iOS team. 

Please check crash report below. 

http://crashes.to/s/4cbf00ca0cb

30
Crashed: brnch_persist_queue
EXC_BREAKPOINT UNKNOWN at 0xe7ffdefe
 raw
0
CoreFoundation	
__CFBasicHashRehash + 19296
1
libsystem_malloc.dylib	
szone_malloc_should_clear + 2730
2
Foundation	
-[NSKeyedArchiver _initWithOutput:] + 392
3
Foundation	
+[NSKeyedArchiver archivedDataWithRootObject:] + 118
4
Shareon1.0	
BNCServerRequestQueue.m line 163
__32-[BNCServerRequestQueue persist]_block_invoke
5	libdispatch.dylib	
_dispatch_call_block_and_release + 10
10	libsystem_pthread.dylib	
_pthread_wqthread + 668

**Comment by aaustin** [comment] 2015-04-29 06:36
Hey @microgomi thanks so much for writing in. We'll dig in and see if we can figure out how this happened. It's not very informative unfortunately :(

**Comment by qinweigong** [comment] 2015-04-29 19:01
Hi @microgomi Could you please let us know which version of our SDK you are using in your app? I tried to find it in our logs with your app key (93179468239078154, correct?) or branch key, but couldn't find any requests from your app in the past few days.
FYI, our current iOS SDK version is 0.6.1. I am trying to find out if the crash was caused by an old SDK which should have the issue fixed in the later versions.

**Comment by microgomi** [comment] 2015-05-01 16:43
Hi @qinweigong.
Thank you for your quick response.
We'd used 0.5.7 SDK version at that time but now we've updated to 0.6.1 version.
The issue could be happened in the 0.5.7 version?
I hope it would be fixed. :-)
thank you.

**Comment by qinweigong** [comment] 2015-05-01 19:23
@microgomi To be honest with you, I don't think there's anything changed with respect to fixing this crash between the two versions.

Based on the crash report, my guess is it's caused by the low memory on that device.
http://crashes.to/s/4cbf00ca0cb/details
As you can see, there's only 1% RAM left, and the crash happened in libsystem_malloc.dylib.
As we are open source, and you can see that we have a try/catch around that block of code. However, as we all know, that'd only catch managed exceptions, but not signals like this one.

**Comment by microgomi** [comment] 2015-05-04 03:49
@qinweigong 
OK, I will check the memory management. 
Thank you very much :-)

**Closed** 2015-05-08 16:36 UTC
